/***********************************************************************************************************
 * Project			    : HR Schema (Based ib Oracle HR Sample Schema)
 * Script Name		  : hr_tables.sql
 * Description		  : Creation of core tables for HR Schema in PostgreSQL 16.1
 * 
 * Database			    : PostgreSQL 16.1
 * Database Engine	: PostgreSQL Native
 * Database Host	  : Aiven - PostgreSQL
 * Schema Name      : HR
 * 
 * Author			      : PaKo Araya
 * E-mail			      : franarayah@gmail.com
 * Company			    : [Personal Project]
 * Created Date		  : 2026-02-10
 * Last Modified	  : 2026-02-10
 * 
 * Script Version	  : 1.0.0
 * Database Version Tested	: 16.1.0
 * Charset			    : UTF8
 * Collation		    : en_US.UTF-8
 * 
 * Dependencies		  : None
 * Related Scripts	:
 * 	- 002_constraints.sql
 * 	- 003_indexes.sql
 * 
 * Execution Tool	  : DBeaver / Postgre CLI
 * Environment		  : [X]Development | [-]Test | [-]Production
 * Execution Mode	  : Manual
 * Backup Needed	  : Yes
 * Rollback Plan	  : Drop created tables
 * Estimated Time	  : < 1 minute
 * Risk Level		    : LOW
 * 
 * Purpose			    : Educational Implementation of Oracle HR Schema in PostgreSQL
 * Compatibilty		  : ANSI SQL Standard + PostgreSQL Extensions
 * Transactional	  : Yes (ACID Compliant)
 * Idempotent		    : Yes
 * 
 * Notes:
 * - This script creates only table structures (DDL).
 * - Circular dependency between DEPARTMENTS and EMPLOYEES is resolved via ALTER TABLE.
 * - Compatible with PostgreSQL 16+
 * 
 * Change Log:
 * --------------------------------------------------------------------------------------------------------
 * Version	| Date 		    | Author	  | Description
 * -------------------------------------------------------------------------------------------------------- 
 * 1.0.0	  | 2026-02-10  | P. Araya	| Initial version - Tables creation
 * 
 * 
 * 
***********************************************************************************************************/

-- DROP THE SCHEMA IF IT EXISTS AND CREATE IT IF IT DOES NOT
DROP SCHEMA IF EXISTS hr CASCADE;

CREATE SCHEMA IF NOT EXISTS hr;
SET search_path TO hr;


-- REGIONS TABLE
CREATE TABLE IF NOT EXISTS regions (
    region_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name    VARCHAR(50) NOT NULL
);


-- COUNTRIES TABLE
CREATE TABLE IF NOT exists countries(
	country_id		INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	country_name	VARCHAR(50) NOT NULL,
	region_id 		INT NOT NULL,
	
	CONSTRAINT fk_countries_regions
		FOREIGN KEY (region_id)
			REFERENCES regions(region_id)
			ON DELETE RESTRICT 
			ON UPDATE CASCADE 
);

-- LOCATIONS TABLE
CREATE TABLE IF NOT EXISTS locations(
  location_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  street_address  VARCHAR(50) NOT NULL,
  postal_code     VARCHAR(15) NOT NULL,
  city            VARCHAR(50) NOT NULL,
  state_province  VARCHAR (30) NOT NULL,
  country_id      INT NOT NULL,
  
  CONSTRAINT fk_locations_countries
    FOREIGN KEY (country_id)
      REFERENCES countries(country_id)
      ON DELETE RESTRICT
      ON UPDATE cascade
);

-- DEPARTMENTS TABLE
CREATE TABLE IF NOT EXISTS departments(
  department_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR(50) NOT NULL,
  manager_id      INT NULL, -- NULL allowed for departments without managers and resolve circular dependency
  location_id     INT NOT NULL,
  
  CONSTRAINT fk_departments_locations
    FOREIGN KEY (location_id)
      REFERENCES locations(location_id)
      ON DELETE RESTRICT 
      ON UPDATE CASCADE   
);

-- JOBS TABLE
CREATE TABLE IF NOT EXISTS jobs(
  job_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_title       VARCHAR(50) NOT NULL,
  min_salary      NUMERIC(12,2) NOT NULL DEFAULT 0,
  max_salary      NUMERIC(12,2) NOT NULL DEFAULT 0,

  CONSTRAINT chk_job_salary_range
    CHECK (min_salary <= max_salary)
);

-- EMPLOYEES TABLE
CREATE TABLE employees(
  employee_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      VARCHAR(50) NOT NULL,
  last_name       VARCHAR(50) NOT NULL,
  email           VARCHAR(100) NOT NULL,
  phone_number    VARCHAR(20),
  hire_date       DATE NOT NULL,
  salary          NUMERIC(12,2) NOT NULL DEFAULT 0,
  commission_pct  DECIMAL(3,2),
  -- NULL allowed for the top-level hierarchy (e.g., President/CEO)
  manager_id      INT NULL,
  job_id          INT NOT NULL,
  department_id   INT NOT NULL,
  
  -- 1.- Relationship with Job Table
  CONSTRAINT fk_employees_jobs
    FOREIGN KEY (job_id)
      REFERENCES jobs(job_id)
      ON DELETE RESTRICT
      ON UPDATE CASCADE, 
      
  -- 2.- Relationship with Departments Table
  CONSTRAINT fk_employees_departments
    FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
      ON DELETE RESTRICT 
      ON UPDATE CASCADE, 
      
  -- 3.- Self-Reference (Manager Relationship)
  -- Establishes a 1:N relationship where an employee reports to another employee
  CONSTRAINT fk_employees_manager
    FOREIGN KEY (manager_id)
      REFERENCES employees(employee_id)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
        
  -- Integrity: No duplicates emails
  CONSTRAINT uq_employee_email
    UNIQUE (email),
        
  -- Basic email format validation for production environment
  CONSTRAINT chk_employee_email_format
    CHECK (email LIKE '%_@__%.__%')
);

-- JOB HISTORY TABLE
CREATE TABLE job_history(
  employee_id     INT NOT NULL,
  start_date      DATE NOT NULL,
  end_date        DATE NOT NULL,
  job_id          INT NOT NULL,
  department_id   INT NOT NULL,
  
  -- Composite Primary Key: An employee can have multiple history records,
  -- but only one starting at a specific date.
  PRIMARY KEY (employee_id, start_date),
  
  -- 1.- Relationship with Employees Table
  CONSTRAINT fk_job_history_employees
    FOREIGN KEY (employee_id)
      REFERENCES employees(employee_id)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  
  -- 2.- Relationship with Job Table
  CONSTRAINT fk_job_history_jobs
    FOREIGN KEY (job_id)
      REFERENCES jobs(job_id)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
      
  -- 3.- Relationship with Departments Table
  CONSTRAINT fk_job_history_departments
    FOREIGN KEY (department_id)
      REFERENCES departments(department_id)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
      
  -- Business logic check:  ensure end_Date is after start_date
  CONSTRAINT chk_job_history_date_range
    CHECK (end_date > start_date)
);

-- CIRCULAR REFERENCE RESOLUTION
-- Linking the department manager to the employees table after both exist
ALTER TABLE departments 
  ADD CONSTRAINT fk_departments_manager
    FOREIGN KEY (manager_id)
      REFERENCES employees(employee_id)
      ON DELETE SET NULL 
      ON UPDATE CASCADE;


