/***********************************************************************************************************
 * Project			    : HR Schema (Based ib Oracle HR Sample Schema)
 * Script Name		  : hr_tables.sql
 * Description		  : Creation of core tables for HR Schema in PostgreSQL 16.1
 * 
 * Database			    : PostgreSQL 16.1
 * Database Engine	: PostgreSQL Native
 * Database Host	  : Aiven - PostgreSQL
 * Schema Name      : HR
 * 
 * Author			      : PaKo Araya
 * E-mail			      : franarayah@gmail.com
 * Company			    : [Personal Project]
 * Created Date		  : 2026-02-10
 * Last Modified	  : 2026-02-10
 * 
 * Script Version	  : 1.0.0
 * Database Version Tested	: 16.1.0
 * Charset			    : UTF8
 * Collation		    : en_US.UTF-8
 * 
 * Dependencies		  : None
 * Related Scripts	:
 * 	- 002_constraints.sql
 * 	- 003_indexes.sql
 * 
 * Execution Tool	  : DBeaver / Postgre CLI
 * Environment		  : [X]Development | [-]Test | [-]Production
 * Execution Mode	  : Manual
 * Backup Needed	  : Yes
 * Rollback Plan	  : Drop created tables
 * Estimated Time	  : < 1 minute
 * Risk Level		    : LOW
 * 
 * Purpose			    : Educational Implementation of Oracle HR Schema in PostgreSQL
 * Compatibilty		  : ANSI SQL Standard + PostgreSQL Extensions
 * Transactional	  : Yes (ACID Compliant)
 * Idempotent		    : Yes
 * 
 * Notes:
 * - This script creates only table structures (DDL).
 * - Circular dependency between DEPARTMENTS and EMPLOYEES is resolved via ALTER TABLE.
 * - Compatible with PostgreSQL 16+
 * 
 * Change Log:
 * --------------------------------------------------------------------------------------------------------
 * Version	| Date 		    | Author	  | Description
 * -------------------------------------------------------------------------------------------------------- 
 * 1.0.0	  | 2026-02-10  | P. Araya	| Initial version - Tables creation
 * 
 * 
 * 
***********************************************************************************************************/

-- Drop the schema if it exists and create it if it does not
CREATE SCHEMA IF NOT EXISTS hr;
SET search_path TO hr;


-- REGIONS TABLE
CREATE TABLE IF NOT EXISTS regions (
    region_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name    VARCHAR(50) NOT NULL
);


-- COUNTRIES TABLE
CREATE TABLE IF NOT exists countries(
	country_id		INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	country_name	VARCHAR(50) NOT NULL,
	region_id 		INT NOT NULL,
	
	CONSTRAINT fk_countries_regions
		FOREIGN KEY (region_id)
			REFERENCES regions(region_id)
			ON DELETE RESTRICT 
			ON UPDATE CASCADE 
);







